### ISSUE TITLE
Milestone 1 - Beating Heart

### ISSUE THREAD

**Issue by dboskovic** [FlatFilers/gecko#1]
Goal: Create a functional proof of concept that allows basic scaffolding with JSX.

## JSX
```jsx
export function() {
  return <Folder name="heartbeat">
    <File name="readme.md">
      <Text>hello world</Text>
    </File>
    <File name="index.js">
      <Function name="helloWorld" export="default">console.log("hello world");</Function>
    </File>
  </Folder>
}
```

## Result
```txt
- /heartbeat
  - readme.md
  - index.js

cat ./heartbeat/index.js
// => export default function helloWorld() { console.log("hello world"); }

cat ./heartbeat/readme.md
// => hello world
```

```[tasklist]
### Tasks
- [x] Setup some version of SSR react (Bun?)
- [x] Create `Folder` component
- [x] Create `File` component
- [x] Create `Text` component
- [x] Create `Function` component
```
