### ISSUE TITLE
Milestone 2 — Baby API

### ISSUE THREAD

**Issue by dboskovic** [FlatFilers/gecko#2]
# ⭐ Goal: Use a folder of Resource definitions to generate an entire working CRUD Restful API.

```[tasklist]
### Tasks
- [x] Generate functional stub controllers
- [x] Generate a functional repository (can just read/write from a .json file for the test)
- [x] Generate a functional openapi.yaml and make sure it passes https://apitools.dev/swagger-parser/online/
- [x] Write or have AI write a basic e2e test proving the generated code works
- [x] Files should be formatted with prettier after generation
- [x] Include schema validation in POST /users and PUT /users/:id
```

## Input

```json
// models/user.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "User",
  "description": "A schema for a user with basic information",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a user",
      "type": "string",
      "pattern": "^[a-zA-Z0-9_-]+$"
    },
    "name": {
      "description": "The user's full name",
      "type": "string",
      "minLength": 1
    },
    "email": {
      "description": "The user's email address",
      "type": "string",
      "format": "email"
    },
    "phoneNumber": {
      "description": "The user's contact phone number",
      "type": "string",
      "pattern": "^[0-9+()-]+$"
    }
  },
  "required": ["id", "name", "email"]
}
```

## Output
```
- controllers
  - users
    - get.ts
    - create.ts
    - update.ts
    - delete.ts
    - list.ts
- resources
  - user.ts
    - new UserResource(props)
      - user.email // setter/getter
      - user.toJSON()
- repositories
  - users.ts
    - getUserById(id): UserResource
    - getAllUsers(): UserResource[]
    - updateUser(id, props): UserResource
    - createUser(props): UserResource
    - deleteUser(id): boolean
openapi.yaml // definition of api
```

## Acceptance Criteria
- Be able to use a Postman to interact with the API
- The only file not code-generated is the user.json file
- A functional e2e test written in jest should verify the basic operations
- Files should be formatted with prettier after generation
