### ISSUE TITLE
New JSX tags needed

### ISSUE THREAD

**Issue by NateFerrero** [FlatFilers/gecko#8]
```[tasklist]
### Tasks
- [x] `<Property>` for class properties
- [x] `<Class implements>` to support class implements
- [x] `<Class extends>` to support class extends
- [x] `<Class abstract>` for abstract classes
- [x] `<Method returnType='string'>` to support class method return TypeScript types
- [x] Filter out `null` children
- [x] Deploy to `@flatfile/gecko` on npm
- [x] Remove `.env` and remove requirement for Claude keys (only if Prompt is used)
```
